name: Release Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Package extension
        run: npm run package

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          files: web-ext-artifacts/bilibili_doremi-*.zip
